name: ScheduledAnnouncer
main: at.co.hohl.Announcer.AnnouncerPlugin
version: 1.6.1
description: Automatically Announce tips and news!
website: http://github.com/hohl/ScheduledAnnouncer
authors:
 - 'Michael Hohl (miho)'
commands:
  announce:
    description: Managing Announcements
    usage: /<command> help - Displays the help for Announcer
  announcer:
    description: Alias for /announce
    usage: /<command> help - Displays the help for Announcer